<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SONHH\eBaySDK\Trading\Types;

/**
 *
 * @property \SONHH\eBaySDK\Trading\Types\ItemListCustomizationType $WatchList
 * @property \SONHH\eBaySDK\Trading\Types\ItemListCustomizationType $BidList
 * @property \SONHH\eBaySDK\Trading\Types\ItemListCustomizationType $BestOfferList
 * @property \SONHH\eBaySDK\Trading\Types\ItemListCustomizationType $WonList
 * @property \SONHH\eBaySDK\Trading\Types\ItemListCustomizationType $LostList
 * @property \SONHH\eBaySDK\Trading\Types\MyeBaySelectionType $FavoriteSearches
 * @property \SONHH\eBaySDK\Trading\Types\MyeBaySelectionType $FavoriteSellers
 * @property \SONHH\eBaySDK\Trading\Types\MyeBaySelectionType $SecondChanceOffer
 * @property \SONHH\eBaySDK\Trading\Types\ItemListCustomizationType $DeletedFromWonList
 * @property \SONHH\eBaySDK\Trading\Types\ItemListCustomizationType $DeletedFromLostList
 * @property \SONHH\eBaySDK\Trading\Types\ItemListCustomizationType $BuyingSummary
 * @property \SONHH\eBaySDK\Trading\Types\MyeBaySelectionType $UserDefinedLists
 * @property boolean $HideVariations
 */
class GetMyeBayBuyingRequestType extends \SONHH\eBaySDK\Trading\Types\AbstractRequestType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'WatchList' => [
            'type' => 'SONHH\eBaySDK\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'WatchList'
        ],
        'BidList' => [
            'type' => 'SONHH\eBaySDK\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BidList'
        ],
        'BestOfferList' => [
            'type' => 'SONHH\eBaySDK\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferList'
        ],
        'WonList' => [
            'type' => 'SONHH\eBaySDK\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'WonList'
        ],
        'LostList' => [
            'type' => 'SONHH\eBaySDK\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LostList'
        ],
        'FavoriteSearches' => [
            'type' => 'SONHH\eBaySDK\Trading\Types\MyeBaySelectionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FavoriteSearches'
        ],
        'FavoriteSellers' => [
            'type' => 'SONHH\eBaySDK\Trading\Types\MyeBaySelectionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FavoriteSellers'
        ],
        'SecondChanceOffer' => [
            'type' => 'SONHH\eBaySDK\Trading\Types\MyeBaySelectionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SecondChanceOffer'
        ],
        'DeletedFromWonList' => [
            'type' => 'SONHH\eBaySDK\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DeletedFromWonList'
        ],
        'DeletedFromLostList' => [
            'type' => 'SONHH\eBaySDK\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DeletedFromLostList'
        ],
        'BuyingSummary' => [
            'type' => 'SONHH\eBaySDK\Trading\Types\ItemListCustomizationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BuyingSummary'
        ],
        'UserDefinedLists' => [
            'type' => 'SONHH\eBaySDK\Trading\Types\MyeBaySelectionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UserDefinedLists'
        ],
        'HideVariations' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'HideVariations'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        if (!array_key_exists(__CLASS__, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[__CLASS__] = 'GetMyeBayBuyingRequest';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
