<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SONHH\eBaySDK\ResolutionCaseManagement\Services;

class ResolutionCaseManagementService extends \SONHH\eBaySDK\ResolutionCaseManagement\Services\ResolutionCaseManagementBaseService
{
    const API_VERSION = '1.3.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\GetVersionRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\GetVersionResponse
     */
    public function getVersion(\SONHH\eBaySDK\ResolutionCaseManagement\Types\GetVersionRequest $request)
    {
        return $this->getVersionAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\GetVersionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVersionAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\GetVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getVersion',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\GetVersionResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\GetUserCasesRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\GetUserCasesResponse
     */
    public function getUserCases(\SONHH\eBaySDK\ResolutionCaseManagement\Types\GetUserCasesRequest $request)
    {
        return $this->getUserCasesAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\GetUserCasesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserCasesAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\GetUserCasesRequest $request)
    {
        return $this->callOperationAsync(
            'getUserCases',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\GetUserCasesResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailResponse
     */
    public function getEBPCaseDetail(\SONHH\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailRequest $request)
    {
        return $this->getEBPCaseDetailAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEBPCaseDetailAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailRequest $request)
    {
        return $this->callOperationAsync(
            'getEBPCaseDetail',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\GetActivityOptionsRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\GetActivityOptionsResponse
     */
    public function getActivityOptions(\SONHH\eBaySDK\ResolutionCaseManagement\Types\GetActivityOptionsRequest $request)
    {
        return $this->getActivityOptionsAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\GetActivityOptionsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getActivityOptionsAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\GetActivityOptionsRequest $request)
    {
        return $this->callOperationAsync(
            'getActivityOptions',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\GetActivityOptionsResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundResponse
     */
    public function issueFullRefund(\SONHH\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundRequest $request)
    {
        return $this->issueFullRefundAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function issueFullRefundAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundRequest $request)
    {
        return $this->callOperationAsync(
            'issueFullRefund',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoResponse
     */
    public function provideTrackingInfo(\SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoRequest $request)
    {
        return $this->provideTrackingInfoAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function provideTrackingInfoAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoRequest $request)
    {
        return $this->callOperationAsync(
            'provideTrackingInfo',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionResponse
     */
    public function offerOtherSolution(\SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionRequest $request)
    {
        return $this->offerOtherSolutionAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function offerOtherSolutionAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionRequest $request)
    {
        return $this->callOperationAsync(
            'offerOtherSolution',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportResponse
     */
    public function escalateToCustomerSupport(\SONHH\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportRequest $request)
    {
        return $this->escalateToCustomerSupportAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function escalateToCustomerSupportAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportRequest $request)
    {
        return $this->callOperationAsync(
            'escalateToCustomerSupport',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportResponse
     */
    public function appealToCustomerSupport(\SONHH\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportRequest $request)
    {
        return $this->appealToCustomerSupportAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function appealToCustomerSupportAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportRequest $request)
    {
        return $this->callOperationAsync(
            'appealToCustomerSupport',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferPartialRefundRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferPartialRefundResponse
     */
    public function offerPartialRefund(\SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferPartialRefundRequest $request)
    {
        return $this->offerPartialRefundAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferPartialRefundRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function offerPartialRefundAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferPartialRefundRequest $request)
    {
        return $this->callOperationAsync(
            'offerPartialRefund',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferPartialRefundResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundResponse
     */
    public function issuePartialRefund(\SONHH\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundRequest $request)
    {
        return $this->issuePartialRefundAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function issuePartialRefundAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundRequest $request)
    {
        return $this->callOperationAsync(
            'issuePartialRefund',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoResponse
     */
    public function provideShippingInfo(\SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoRequest $request)
    {
        return $this->provideShippingInfoAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function provideShippingInfoAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoRequest $request)
    {
        return $this->callOperationAsync(
            'provideShippingInfo',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideReturnInfoRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideReturnInfoResponse
     */
    public function provideReturnInfo(\SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideReturnInfoRequest $request)
    {
        return $this->provideReturnInfoAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideReturnInfoRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function provideReturnInfoAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideReturnInfoRequest $request)
    {
        return $this->callOperationAsync(
            'provideReturnInfo',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideReturnInfoResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoResponse
     */
    public function provideRefundInfo(\SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoRequest $request)
    {
        return $this->provideRefundInfoAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function provideRefundInfoAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoRequest $request)
    {
        return $this->callOperationAsync(
            'provideRefundInfo',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\UploadDocumentsRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\UploadDocumentsResponse
     */
    public function uploadDocuments(\SONHH\eBaySDK\ResolutionCaseManagement\Types\UploadDocumentsRequest $request)
    {
        return $this->uploadDocumentsAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\UploadDocumentsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadDocumentsAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\UploadDocumentsRequest $request)
    {
        return $this->callOperationAsync(
            'uploadDocuments',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\UploadDocumentsResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferRefundUponReturnRequest $request
     * @return \SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferRefundUponReturnResponse
     */
    public function offerRefundUponReturn(\SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferRefundUponReturnRequest $request)
    {
        return $this->offerRefundUponReturnAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferRefundUponReturnRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function offerRefundUponReturnAsync(\SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferRefundUponReturnRequest $request)
    {
        return $this->callOperationAsync(
            'offerRefundUponReturn',
            $request,
            '\SONHH\eBaySDK\ResolutionCaseManagement\Types\OfferRefundUponReturnResponse'
        );
    }
}
