<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SONHH\eBaySDK\Inventory\Types;

/**
 *
 * @property \SONHH\eBaySDK\Inventory\Types\Fee[] $fees
 * @property \SONHH\eBaySDK\Inventory\Enums\MarketplaceEnum $marketplaceId
 * @property \SONHH\eBaySDK\Inventory\Types\ErrorDetailV3[] $warnings
 */
class FeeSummary extends \SONHH\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'fees' => [
            'type' => 'SONHH\eBaySDK\Inventory\Types\Fee',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'fees'
        ],
        'marketplaceId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'marketplaceId'
        ],
        'warnings' => [
            'type' => 'SONHH\eBaySDK\Inventory\Types\ErrorDetailV3',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'warnings'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
