<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SONHH\eBaySDK\Finding\Services;

class FindingService extends \SONHH\eBaySDK\Finding\Services\FindingBaseService
{
    const API_VERSION = '1.13.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\GetSearchKeywordsRecommendationRequest $request
     * @return \SONHH\eBaySDK\Finding\Types\GetSearchKeywordsRecommendationResponse
     */
    public function getSearchKeywordsRecommendation(\SONHH\eBaySDK\Finding\Types\GetSearchKeywordsRecommendationRequest $request)
    {
        return $this->getSearchKeywordsRecommendationAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\GetSearchKeywordsRecommendationRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSearchKeywordsRecommendationAsync(\SONHH\eBaySDK\Finding\Types\GetSearchKeywordsRecommendationRequest $request)
    {
        return $this->callOperationAsync(
            'getSearchKeywordsRecommendation',
            $request,
            '\SONHH\eBaySDK\Finding\Types\GetSearchKeywordsRecommendationResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsByKeywordsRequest $request
     * @return \SONHH\eBaySDK\Finding\Types\FindItemsByKeywordsResponse
     */
    public function findItemsByKeywords(\SONHH\eBaySDK\Finding\Types\FindItemsByKeywordsRequest $request)
    {
        return $this->findItemsByKeywordsAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsByKeywordsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsByKeywordsAsync(\SONHH\eBaySDK\Finding\Types\FindItemsByKeywordsRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsByKeywords',
            $request,
            '\SONHH\eBaySDK\Finding\Types\FindItemsByKeywordsResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsByCategoryRequest $request
     * @return \SONHH\eBaySDK\Finding\Types\FindItemsByCategoryResponse
     */
    public function findItemsByCategory(\SONHH\eBaySDK\Finding\Types\FindItemsByCategoryRequest $request)
    {
        return $this->findItemsByCategoryAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsByCategoryRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsByCategoryAsync(\SONHH\eBaySDK\Finding\Types\FindItemsByCategoryRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsByCategory',
            $request,
            '\SONHH\eBaySDK\Finding\Types\FindItemsByCategoryResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsAdvancedRequest $request
     * @return \SONHH\eBaySDK\Finding\Types\FindItemsAdvancedResponse
     */
    public function findItemsAdvanced(\SONHH\eBaySDK\Finding\Types\FindItemsAdvancedRequest $request)
    {
        return $this->findItemsAdvancedAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsAdvancedRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsAdvancedAsync(\SONHH\eBaySDK\Finding\Types\FindItemsAdvancedRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsAdvanced',
            $request,
            '\SONHH\eBaySDK\Finding\Types\FindItemsAdvancedResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsByProductRequest $request
     * @return \SONHH\eBaySDK\Finding\Types\FindItemsByProductResponse
     */
    public function findItemsByProduct(\SONHH\eBaySDK\Finding\Types\FindItemsByProductRequest $request)
    {
        return $this->findItemsByProductAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsByProductRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsByProductAsync(\SONHH\eBaySDK\Finding\Types\FindItemsByProductRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsByProduct',
            $request,
            '\SONHH\eBaySDK\Finding\Types\FindItemsByProductResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsIneBayStoresRequest $request
     * @return \SONHH\eBaySDK\Finding\Types\FindItemsIneBayStoresResponse
     */
    public function findItemsIneBayStores(\SONHH\eBaySDK\Finding\Types\FindItemsIneBayStoresRequest $request)
    {
        return $this->findItemsIneBayStoresAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsIneBayStoresRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsIneBayStoresAsync(\SONHH\eBaySDK\Finding\Types\FindItemsIneBayStoresRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsIneBayStores',
            $request,
            '\SONHH\eBaySDK\Finding\Types\FindItemsIneBayStoresResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsByImageRequest $request
     * @return \SONHH\eBaySDK\Finding\Types\FindItemsByImageResponse
     */
    public function findItemsByImage(\SONHH\eBaySDK\Finding\Types\FindItemsByImageRequest $request)
    {
        return $this->findItemsByImageAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsByImageRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsByImageAsync(\SONHH\eBaySDK\Finding\Types\FindItemsByImageRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsByImage',
            $request,
            '\SONHH\eBaySDK\Finding\Types\FindItemsByImageResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\GetHistogramsRequest $request
     * @return \SONHH\eBaySDK\Finding\Types\GetHistogramsResponse
     */
    public function getHistograms(\SONHH\eBaySDK\Finding\Types\GetHistogramsRequest $request)
    {
        return $this->getHistogramsAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\GetHistogramsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHistogramsAsync(\SONHH\eBaySDK\Finding\Types\GetHistogramsRequest $request)
    {
        return $this->callOperationAsync(
            'getHistograms',
            $request,
            '\SONHH\eBaySDK\Finding\Types\GetHistogramsResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\GetVersionRequest $request
     * @return \SONHH\eBaySDK\Finding\Types\GetVersionResponse
     */
    public function getVersion(\SONHH\eBaySDK\Finding\Types\GetVersionRequest $request)
    {
        return $this->getVersionAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\GetVersionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVersionAsync(\SONHH\eBaySDK\Finding\Types\GetVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getVersion',
            $request,
            '\SONHH\eBaySDK\Finding\Types\GetVersionResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsForFavoriteSearchRequest $request
     * @return \SONHH\eBaySDK\Finding\Types\FindItemsForFavoriteSearchResponse
     */
    public function findItemsForFavoriteSearch(\SONHH\eBaySDK\Finding\Types\FindItemsForFavoriteSearchRequest $request)
    {
        return $this->findItemsForFavoriteSearchAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindItemsForFavoriteSearchRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findItemsForFavoriteSearchAsync(\SONHH\eBaySDK\Finding\Types\FindItemsForFavoriteSearchRequest $request)
    {
        return $this->callOperationAsync(
            'findItemsForFavoriteSearch',
            $request,
            '\SONHH\eBaySDK\Finding\Types\FindItemsForFavoriteSearchResponse'
        );
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindCompletedItemsRequest $request
     * @return \SONHH\eBaySDK\Finding\Types\FindCompletedItemsResponse
     */
    public function findCompletedItems(\SONHH\eBaySDK\Finding\Types\FindCompletedItemsRequest $request)
    {
        return $this->findCompletedItemsAsync($request)->wait();
    }

    /**
     * @param \SONHH\eBaySDK\Finding\Types\FindCompletedItemsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findCompletedItemsAsync(\SONHH\eBaySDK\Finding\Types\FindCompletedItemsRequest $request)
    {
        return $this->callOperationAsync(
            'findCompletedItems',
            $request,
            '\SONHH\eBaySDK\Finding\Types\FindCompletedItemsResponse'
        );
    }
}
