<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace SONHH\eBaySDK\PostOrder\Types;

/**
 *
 * @property string $caseId
 * @property \SONHH\eBaySDK\PostOrder\Types\ReturnEligibilityErrorDetailType[] $eligibilityErrorDetail
 * @property \SONHH\eBaySDK\PostOrder\Types\StatusType $eligibilityStatus
 * @property \SONHH\eBaySDK\PostOrder\Types\DateTime $eligibleStartDate
 * @property \SONHH\eBaySDK\PostOrder\Types\DateTime $returnCreationDate
 * @property \SONHH\eBaySDK\PostOrder\Types\DateTime $returnDeadline
 * @property string $returnId
 */
class EligibilityResultType extends \SONHH\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'caseId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'caseId'
        ],
        'eligibilityErrorDetail' => [
            'type' => 'SONHH\eBaySDK\PostOrder\Types\ReturnEligibilityErrorDetailType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'eligibilityErrorDetail'
        ],
        'eligibilityStatus' => [
            'type' => 'SONHH\eBaySDK\PostOrder\Types\StatusType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eligibilityStatus'
        ],
        'eligibleStartDate' => [
            'type' => 'SONHH\eBaySDK\PostOrder\Types\DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eligibleStartDate'
        ],
        'returnCreationDate' => [
            'type' => 'SONHH\eBaySDK\PostOrder\Types\DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'returnCreationDate'
        ],
        'returnDeadline' => [
            'type' => 'SONHH\eBaySDK\PostOrder\Types\DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'returnDeadline'
        ],
        'returnId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'returnId'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
